### ISSUE TITLE
Installation on Ubuntu successful but using failed

### ISSUE THREAD

**Issue by lowks** [ekalinin/envirius#18]
I am using: 

1. zsh
2. Ubuntu

When I try to do `nv mk elixir_latest` it is successful, but then when I tro to activate it using `nv activate elixir_latest` I get the following:

```
~/S/envirius ❯❯❯ nv activate elixir_latest                                                                                                      master
complete:13: command not found: compdef
complete:13: command not found: compdef
Environment elixir_latest activated.
```

**Comment by lowks** [comment]
Ah, I see. I was supposed to do it like this: `nv mk elixir_latest --elixir=1.3.1`

**Comment by ekalinin** [comment]
> Ah, I see. I was supposed to do it like this: `nv mk elixir_latest --elixir=1.3.1`

Yep :)
